// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type RedirectionMap struct {
	Uid       string    `json:"uid"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
}
