// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: redirection_map.sql

package db

import (
	"context"
)

const createRedirectionMap = `-- name: CreateRedirectionMap :one
INSERT INTO redirection_map (uid, url)
VALUES ($1, $2)
RETURNING uid, url, created_at
`

type CreateRedirectionMapParams struct {
	Uid string `json:"uid"`
	Url string `json:"url"`
}

func (q *Queries) CreateRedirectionMap(ctx context.Context, arg CreateRedirectionMapParams) (RedirectionMap, error) {
	row := q.db.QueryRowContext(ctx, createRedirectionMap, arg.Uid, arg.Url)
	var i RedirectionMap
	err := row.Scan(&i.Uid, &i.Url, &i.CreatedAt)
	return i, err
}

const getRedirectionMap = `-- name: GetRedirectionMap :one
SELECT uid, url, created_at
from redirection_map
WHERE uid = $1
LIMIT 1
`

func (q *Queries) GetRedirectionMap(ctx context.Context, uid string) (RedirectionMap, error) {
	row := q.db.QueryRowContext(ctx, getRedirectionMap, uid)
	var i RedirectionMap
	err := row.Scan(&i.Uid, &i.Url, &i.CreatedAt)
	return i, err
}
