// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: redirection_map.sql

package db

import (
	"context"
)

const createRedirectionMap = `-- name: CreateRedirectionMap :one
INSERT INTO redirection_map (uuid, url)
VALUES ($1, $2)
RETURNING uuid, url, created_at
`

type CreateRedirectionMapParams struct {
	Uuid string `json:"uuid"`
	Url  string `json:"url"`
}

func (q *Queries) CreateRedirectionMap(ctx context.Context, arg CreateRedirectionMapParams) (RedirectionMap, error) {
	row := q.db.QueryRowContext(ctx, createRedirectionMap, arg.Uuid, arg.Url)
	var i RedirectionMap
	err := row.Scan(&i.Uuid, &i.Url, &i.CreatedAt)
	return i, err
}

const getRedirectionMap = `-- name: GetRedirectionMap :one
SELECT uuid, url, created_at
from redirection_map
WHERE uuid = $1
LIMIT 1
`

func (q *Queries) GetRedirectionMap(ctx context.Context, uuid string) (RedirectionMap, error) {
	row := q.db.QueryRowContext(ctx, getRedirectionMap, uuid)
	var i RedirectionMap
	err := row.Scan(&i.Uuid, &i.Url, &i.CreatedAt)
	return i, err
}
