// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"time"
)

type UrlMap struct {
	Uid       string    `json:"uid"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
}
