// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
	"time"
)

type UrlMap struct {
	Uid            string        `json:"uid"`
	Url            string        `json:"url"`
	TimeRedirected sql.NullInt64 `json:"time_redirected"`
	CreatedAt      time.Time     `json:"created_at"`
}
