name: deploy server
on: 
  push: 
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        port: ${{ secrets.SSH_PORT }}
        script: | 
          cd ~/surelink
          git pull --rebase
          docker-compose -f docker-compose-go.yaml up --build -d
          docker-compose -f docker-compose-vue.yaml up --build -d
          
