steps:
  - name: Install SSH Key
    uses: shimataro/ssh-key-action@v2
    with:
      key: {%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }}
      known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    
